name = "hoa-advocate"
compatibility_date = "2025-04-01"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[vars]
NODE_VERSION = "18.18.0"

[[d1_databases]]
binding = "DB"
database_name = "hoa-db"
database_id = "e3b3ba44-7cd3-404e-baa0-32cbc7c049e8"
migrations_dir = 'drizzle'