name = "hoa-advocate"
compatibility_date = "2025-04-01"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[vars]
NODE_VERSION = "18.18.0"

[[d1_databases]]
binding = "DB"
database_name = "hoa-db"
database_id = "b8ebb0cb-c1c2-4f89-a75a-5890296ff7b0"
migrations_dir = 'drizzle'